[package]
name = "ui_layout"
version = "0.11.0"
edition = "2024"

description = "A minimal Flexbox-inspired layout engine for Rust GUI"
repository = "https://github.com/098orin/ui_layout-rs"
license = "MIT"
keywords = ["flexbox", "gui", "layout", "ui"]
categories = ["gui"]

[features]
layout-bench = []
unstable = []
